### ISSUE TITLE
Quadratically shifted bases

### ISSUE THREAD

**Issue by TSGut** [JuliaApproximation/ClassicalOrthogonalPolynomials.jl#103]
I want to use $P(2x^2-1)$. I had this working when the repo was still OrthogonalPolynomialsQuasi.jl but some changes since have stopped it from working with my setup and I don't want to use the old repo. I think this should just be easy to do out of the box in this package, especially given how ubiquitous $P(2x^2-1)$ is for rotationally symmetric bases.

It seems a Chebyhev quadratic shift is implemented in the tests, see https://github.com/JuliaApproximation/ClassicalOrthogonalPolynomials.jl/blob/139fee6e6c3a4c081316f82396337464b5675d6f/test/test_chebyshev.jl#L478

I think this should be low effort to get working for at least general Jacobi polynomials. Any objections to me adding this functionality to the package itself rather than just have it defined in tests?

Once we do this I would also be happy to type up some documentation on shifted bases. :grin:

**Comment by dlfivefifty** [comment]
Are mappings really the right way to do this? It might be better to think of these as `SymmetricLegendre` living in SymmetricOrthogonalPolynomials.jl as then the symmetry aspect is explicit....

**Comment by dlfivefifty** [comment]
Yes I think that's sensible... I think it would be a mistake to widen the scope of this package TBH

**Comment by TSGut** [comment]
Great, I'll start work on including it in EquilibriumMeasures.jl for now and will open an issue in SymmetricOrthogonalPolynomials.jl to remind myself to add it there when we know more about how that package will be organized.
