### ISSUE TITLE
long compilation time for Jacobi(m,n) \ Jacobi(0,0)

### ISSUE THREAD

**Issue by putianyi889** [JuliaApproximation/ClassicalOrthogonalPolynomials.jl#136]
```julia
julia> using ClassicalOrthogonalPolynomials

julia> @time Jacobi(2,2) \ Jacobi(0,0);
  0.206673 seconds (326.39 k allocations: 19.069 MiB, 98.56% compilation time)

julia> @time Jacobi(5,5) \ Jacobi(0,0);
  0.435400 seconds (788.60 k allocations: 43.161 MiB, 98.64% compilation time)

julia> @time Jacobi(10,10) \ Jacobi(0,0);
 16.587771 seconds (26.72 M allocations: 1.142 GiB, 1.86% gc time, 99.94% compilation time)

julia> @time Jacobi(11,11) \ Jacobi(0,0);
 46.804348 seconds (75.86 M allocations: 3.206 GiB, 1.57% gc time, 100.00% compilation time)

julia> @time Jacobi(11,11) \ Jacobi(0,0);
  0.000060 seconds (43 allocations: 20.266 KiB)
```

This could possibly be caused by LazyArrays.ApplyArray using NTuple.

**Comment by putianyi889** [comment]
https://github.com/JuliaArrays/LazyArrays.jl/issues/198

**Comment by dlfivefifty** [comment]
It's most likely an issue in `simplifiable`

https://github.com/JuliaArrays/LazyArrays.jl/blob/940fbc7eea9ca5dacfb60f3ca24a2189d9540864/src/linalg/mul.jl#L303

where compile time grows exponentially with the number of arguments (it recursively checks whether the the front of the arguments are simpilifiable and then the tail, meaning a lot is checked multiple times). This could be reduced to linear using a for loop in a generated that looks at just pairs and triplets to see if they are simplifiable (I don't think we have 4-arg simplifies).

**Comment by TSGut** [comment]
@putianyi889 So was this fixed by https://github.com/JuliaApproximation/ClassicalOrthogonalPolynomials.jl/pull/145 and can thus be closed?
