### ISSUE TITLE
UndefVarError in docs

### ISSUE THREAD

**Issue by TSGut** [JuliaApproximation/ClassicalOrthogonalPolynomials.jl#166]
What's going on in the docs that almost all lines of code evaluate to `UndefVarError`?

**Comment by dlfivefifty** [comment]
probably each block is run independently so somewhere there needs to be a "setup".... don't remember how to do this

**Comment by dlfivefifty** [comment]
It's fixed on dev so will work on next tag:

https://juliaapproximation.github.io/ClassicalOrthogonalPolynomials.jl/dev/
