### ISSUE TITLE
Laguerre

### ISSUE THREAD

**Issue by gideonsimpson** [JuliaApproximation/ClassicalOrthogonalPolynomials.jl#18]
Is this package expected to, at some point, include the Laguerre polynomials (for evaluation), or are they already in some other package?

**Comment by dlfivefifty** [comment]
Yes: there was a PR back when it was still called OrthogonalPolynomialsQuasi.jl: https://github.com/JuliaApproximation/OrthogonalPolynomialsQuasi.jl/pull/22

I'll try to resume this now (it's super easy to add OPs).

**Comment by dlfivefifty** [comment]
I've added `laguerrel` to https://github.com/JuliaApproximation/ClassicalOrthogonalPolynomials.jl/pull/19
