### ISSUE TITLE
Multithreading Legendre transform

### ISSUE THREAD

**Issue by ioannisPApapadopoulos** [JuliaApproximation/ClassicalOrthogonalPolynomials.jl#204]
Hi @dlfivefifty @MikaelSlevinsky ! I am not sure whether this should go here or in FastTransforms.jl, sorry! 

I have a problem where I need to apply the Legendre transform to many independent vectors and I would like to multithread the `for loop` in order to speed things up. However, I am running into some unexpected behaviour. It feels like I am encountering some kind of data race but it's not obvious to me what is causing the problem. Here is a MWE:
:
```
>> julia --threads 4
using ClassicalOrthogonalPolynomials
P, p = Legendre(), 5
plP = plan_transform(P, p)

data = zeros(p, p)
for j in 1:p
    ex = plP \ Vector{Float64}(1:p .== j)
    data[:, j] = plP * ex
end

threaded_data = zeros(p, p)
Threads.@threads for j in 1:p
    ex = plP \ Vector{Float64}(1:p .== j)
    threaded_data[:, j] = plP * ex
end
threaded_data ≈ data # (spuriously) false
```

If I use `P=Chebyshev()`, then everything seems to work fine. Is there some sort of multithreading in the Hankel-dot-Toeplitz transform that's interfering with the for loop?

**Comment by dlfivefifty** [comment]
Rule number 1 for multithreading: Don't do it!

There is no reason to assume `plan_transform` is thread-safe. In fact plans are almost never thread safe: they store temporary working vectors which are change.

**Comment by dlfivefifty** [comment]
Instead: do a matrix transform. The multithreading is taken care of by LibFastTransforms
