### ISSUE TITLE
Add Associated(::OrthogonalPolynomial)

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/ClassicalOrthogonalPolynomials.jl#25]
I think we want to support e.g. `Associated(Legendre())` for the associated OPs. It should be straight forward;
```julia
struct Associated{T, PP} <: OrthogonalPolynomial{T}
   P::PP
end

function jacobimatrix(Q::Associated)
    X = jacobimatrix(Q.P)
    c,a,b = subdiagonaldata(X), diagonaldata(X), supdiagonaldata(X)
    Tridiagonal(c[2:end], a[2:end], b[2:end])
end
```
@MikaelSlevinsky Are there any other features I should add? Do you have that the transforms implemented yet?

We could also support `Associated(Legendre(), m)` for more general case.

**Comment by MikaelSlevinsky** [comment]
Yes, we can. Associated Jacobi--Jacobi transforms are defined here https://github.com/JuliaApproximation/FastTransforms.jl/blob/2ee166d75ab09b8b444fb18b6a251ba74df5c10a/src/libfasttransforms.jl#L526 for example, in Float64. There's also a Float32 version.

The associated Laguerre and Hermite are best done directly at the moment. For this, we could `ccall` these functions https://github.com/MikaelSlevinsky/FastTransforms/blob/ecababf53d31cf62eef168714d67b786fbcb93ce/src/ftinternal.h#L360-L362 to get dense triangular matrices. (Nothing about Laguerre and Hermite is fast at the moment anyway.)
